### ISSUE TITLE
global-buffer-overflow

### ISSUE THREAD

**Issue by tianxiaogu** [Kjuly/pngcrush#5]
We are able to trigger a global-buffer-overflow with the attached input.

```
unzip 0.zip
pngcrush -reduce 0 /dev/null
```

[0.zip](https://github.com/Kjuly/pngcrush/files/2373460/0.zip)

```
 | pngcrush-1.8.1
 |    Copyright (C) 1998-2002, 2006-2016 Glenn Randers-Pehrson
 |    Portions Copyright (C) 2005 Greg Roelofs
 | This is a free, open-source program.  Permission is irrevocably
 | granted to everyone to use this version of pngcrush without
 | payment of any fee.
 | Executable name is pngcrush
 | It was built with   bundled libpng-1.6.21
 | and is running with bundled libpng-1.6.21
 |    Copyright (C) 1998-2004, 2006-2016 Glenn Randers-Pehrson,
 |    Copyright (C) 1996, 1997 Andreas Dilger,
 |    Copyright (C) 1995, Guy Eric Schalnat, Group 42 Inc.,
 | and bundled zlib-1.2.8, Copyright (C) 1995-2013,
 |    Jean-loup Gailly and Mark Adler.
 | It was compiled with gcc version 4.2.1 Compatible Clang 8.0.0 (trunk 341771).

   Reading IEND chunk.
   Recompressing IDAT chunks in output/crashes/id:000000,sig:06,src:000033+000211,op:splice,rep:2
   Total length of data found in critical chunks            =        45
While converting output/crashes/id:000000,sig:06,src:000033+000211,op:splice,rep:2 to /dev/null:
  pngcrush caught libpng error:
   IEND: out of place

=================================================================
==32122==ERROR: AddressSanitizer: global-buffer-overflow on address 0x0000011f759c at pc 0x000000571eca bp 0x7ffea800a8d0 sp 0x7ffea800a8c8
WRITE of size 4 at 0x0000011f759c thread T0
    #0 0x571ec9 in main /home/t/Projects/afl/fuzzing-experiments/subjects/pngcrush/pngcrush/pngcrush.c:7133:32
    #1 0x7ff1019b2b96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
    #2 0x41ac09 in _start (/home/t/Projects/afl/fuzzing-experiments/subjects/pngcrush/pngcrush/pngcrush+0x41ac09)

0x0000011f759c is located 0 bytes to the right of global variable 'idat_length' defined in 'pngcrush.c:1940:20' (0x11f7340) of size 604
SUMMARY: AddressSanitizer: global-buffer-overflow /home/t/Projects/afl/fuzzing-experiments/subjects/pngcrush/pngcrush/pngcrush.c:7133:32 in main
Shadow bytes around the buggy address:
  0x000080236e60: 00 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 00
  0x000080236e70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x000080236e80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x000080236e90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x000080236ea0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x000080236eb0: 00 00 00[04]f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x000080236ec0: f9 f9 f9 f9 04 f9 f9 f9 f9 f9 f9 f9 04 f9 f9 f9
  0x000080236ed0: f9 f9 f9 f9 04 f9 f9 f9 f9 f9 f9 f9 04 f9 f9 f9
  0x000080236ee0: f9 f9 f9 f9 01 f9 f9 f9 f9 f9 f9 f9 01 f9 f9 f9
  0x000080236ef0: f9 f9 f9 f9 01 f9 f9 f9 f9 f9 f9 f9 01 f9 f9 f9
  0x000080236f00: f9 f9 f9 f9 04 f9 f9 f9 f9 f9 f9 f9 04 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==32122==ABORTING
```

**Comment by Kjuly** [comment]
Hi @tianxiaogu , for pngcrush lib source code related issue, I'm sorry i can't provide help on it. Plz feedback to the author (glennrp@users.sf.net). Thank you. :)

**Comment by tianxiaogu** [comment]
Hi @Kjuly . thanks for your reply. At first, I thought it may be some error in the `main.c`. I will check it with the original `pngcrush`.
